openai:
  api_key: ${OPENROUTER_API_KEY}
  model: openrouter/openai/gpt-4
  temperature: 0.3
  max_tokens: 1000

stt:
  model: "large-v3"
  language: "auto"
  device: "auto"
  compute_type: "float16"

rag:
  embedding_model: sentence-transformers/all-MiniLM-L6-v2
  chunk_size: 500
  chunk_overlap: 50
  top_k: 3
  similarity_threshold: 0.7
  vector_store: chromadb



